language: go
sudo: false
matrix:
  include:
    - go: 1.x
      env: LATEST=true
    - go: 1.5
    - go: 1.6
    - go: 1.7
    - go: tip
  allow_failures:
    - go: tip

script:
  - go get -t -v ./...
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -v -race ./...
